# Generated by Django 5.2.14 on 2026-05-27 16:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_campus_branding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=80)),
                ('weekly_periods', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)])),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_allocations', to='core.campus')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to='core.classsection')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['campus__name', 'section__grade_name', 'section__section_name', 'subject'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'date', 'subject')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['section', 'date', 'subject'], name='core_attend_section_dbaec9_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectallocation',
            index=models.Index(fields=['teacher', 'is_active'], name='core_teache_teacher_a31284_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectallocation',
            index=models.Index(fields=['campus', 'subject'], name='core_teache_campus__b6713c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectallocation',
            unique_together={('section', 'teacher', 'subject')},
        ),
    ]
