# Generated by Django 5.2.14 on 2026-05-29 09:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_campus_database_config_remove_parent_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'All users'), ('admins', 'Admins'), ('staff', 'Teachers and staff'), ('learners', 'Students and parents')], default='all', max_length=20),
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel_name', models.CharField(max_length=120)),
                ('room_number', models.CharField(max_length=40)),
                ('floor', models.CharField(blank=True, max_length=40)),
                ('capacity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_rooms', to='core.campus')),
            ],
            options={
                'ordering': ['campus__name', 'hostel_name', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed_number', models.CharField(max_length=40)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='core.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.hostelroom')),
            ],
            options={
                'ordering': ['student__first_name', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accession_number', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('author', models.CharField(blank=True, max_length=160)),
                ('isbn', models.CharField(blank=True, max_length=40)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('total_copies', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('shelf_location', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('lost', 'Lost')], default='active', max_length=20)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_books', to='core.campus')),
            ],
            options={
                'ordering': ['title', 'accession_number'],
            },
        ),
        migrations.CreateModel(
            name='LibraryLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('due_on', models.DateField()),
                ('returned_on', models.DateField(blank=True, null=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='issued', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='core.librarybook')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_loans', to='core.campus')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_loans', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_loans', to='core.student')),
            ],
            options={
                'ordering': ['status', 'due_on', '-issued_on'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(max_length=40, unique=True)),
                ('designation', models.CharField(max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('joining_date', models.DateField()),
                ('qualification', models.CharField(blank=True, max_length=180)),
                ('emergency_contact', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('exited', 'Exited')], default='active', max_length=20)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='core.campus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['campus__name', 'employee_code'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=80)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=80)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='core.campus')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='core.classsection')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time', 'section__grade_name', 'section__section_name'],
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('route_code', models.CharField(max_length=40, unique=True)),
                ('start_point', models.CharField(max_length=120)),
                ('end_point', models.CharField(max_length=120)),
                ('stops', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='core.campus')),
            ],
            options={
                'ordering': ['campus__name', 'route_code'],
            },
        ),
        migrations.CreateModel(
            name='TransportVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_number', models.CharField(max_length=40, unique=True)),
                ('driver_name', models.CharField(max_length=120)),
                ('driver_phone', models.CharField(blank=True, max_length=40)),
                ('capacity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('gps_device_id', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_vehicles', to='core.campus')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core.transportroute')),
            ],
            options={
                'ordering': ['campus__name', 'vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentTransportAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_stop', models.CharField(max_length=120)),
                ('drop_stop', models.CharField(max_length=120)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_assignments', to='core.student')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='core.transportroute')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assignments', to='core.transportvehicle')),
            ],
            options={
                'ordering': ['student__first_name', 'start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='hostelroom',
            index=models.Index(fields=['campus', 'is_active'], name='core_hostel_campus__1d77f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hostelroom',
            unique_together={('campus', 'hostel_name', 'room_number')},
        ),
        migrations.AddIndex(
            model_name='hostelallocation',
            index=models.Index(fields=['room', 'is_active'], name='core_hostel_room_id_5de462_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelallocation',
            index=models.Index(fields=['student', 'is_active'], name='core_hostel_student_35443d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hostelallocation',
            unique_together={('room', 'bed_number', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='librarybook',
            index=models.Index(fields=['campus', 'status'], name='core_librar_campus__80f854_idx'),
        ),
        migrations.AddIndex(
            model_name='librarybook',
            index=models.Index(fields=['category'], name='core_librar_categor_de3062_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryloan',
            index=models.Index(fields=['campus', 'status'], name='core_librar_campus__44eeed_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryloan',
            index=models.Index(fields=['student', 'status'], name='core_librar_student_1ebf36_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryloan',
            index=models.Index(fields=['staff_user', 'status'], name='core_librar_staff_u_225e18_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['campus', 'status'], name='core_staffp_campus__7e86e7_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['department'], name='core_staffp_departm_918c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['campus', 'day_of_week'], name='core_timeta_campus__d6a2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['teacher', 'day_of_week'], name='core_timeta_teacher_c18684_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('section', 'day_of_week', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='transportroute',
            index=models.Index(fields=['campus', 'is_active'], name='core_transp_campus__4255ff_idx'),
        ),
        migrations.AddIndex(
            model_name='transportvehicle',
            index=models.Index(fields=['campus', 'is_active'], name='core_transp_campus__9d3705_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttransportassignment',
            index=models.Index(fields=['route', 'is_active'], name='core_studen_route_i_475491_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studenttransportassignment',
            unique_together={('student', 'route', 'start_date')},
        ),
    ]
