# Generated by Django 5.2.14 on 2026-06-04 08:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_announcement_audience_hostelroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=32)),
                ('feature', models.CharField(max_length=80)),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('document_type', models.CharField(max_length=80)),
                ('file_url', models.URLField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('trigger', models.CharField(max_length=80)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['campus__name', 'channel', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('recipient', models.CharField(max_length=180)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_reference', models.CharField(blank=True, max_length=160)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='razorpay', max_length=40)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank'), ('online', 'Online')], default='online', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, max_length=120)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=120)),
                ('gateway_signature', models.CharField(blank=True, max_length=255)),
                ('receipt_number', models.CharField(blank=True, max_length=80)),
                ('webhook_verified', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['campus__name', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('present_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('absent_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('leave_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('half_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_status', models.CharField(choices=[('draft', 'Draft'), ('payable', 'Payable'), ('paid', 'Paid'), ('hold', 'Hold')], default='draft', max_length=20)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('slip_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['-year', '-month', 'staff_user__username'],
            },
        ),
        migrations.AddField(
            model_name='campus',
            name='academic_year_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='campus',
            name='attendance_hardware_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campus',
            name='banner_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='billing_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='campus',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='campus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campuses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campus',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campus',
            name='messaging_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campus',
            name='monthly_subscription_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='campus',
            name='payment_gateway_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campus',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='campus',
            name='subscription_plan',
            field=models.CharField(blank=True, default='Standard', max_length=80),
        ),
        migrations.AddField(
            model_name='campus',
            name='subscription_status',
            field=models.CharField(blank=True, default='active', max_length=40),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'All users'), ('admins', 'Admins'), ('staff', 'Teachers and staff'), ('learners', 'Students and parent view')], default='all', max_length=20),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['code', 'status'], name='core_campus_code_2f74b4_idx'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['subscription_status'], name='core_campus_subscri_4a772c_idx'),
        ),
        migrations.AddField(
            model_name='ailog',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='core.campus'),
        ),
        migrations.AddField(
            model_name='ailog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ailog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.campus'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.student'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='core.campus'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='core.campus'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.student'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.messagetemplate'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='core.campus'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='fee_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.feeassignment'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.payment'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='core.student'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.campus'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_settings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='core.campus'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_records_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='staff_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ailog',
            index=models.Index(fields=['campus', 'role', 'feature'], name='core_ailog_campus__e32925_idx'),
        ),
        migrations.AddIndex(
            model_name='ailog',
            index=models.Index(fields=['user', 'created_at'], name='core_ailog_user_id_8d472c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['campus', 'document_type', 'status'], name='core_docume_campus__d0cc53_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['student', 'document_type'], name='core_docume_student_76bca8_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['campus', 'channel', 'status'], name='core_messag_campus__2f98d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together={('campus', 'name', 'channel')},
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['campus', 'channel', 'status'], name='core_outbou_campus__278724_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['recipient_user', 'created_at'], name='core_outbou_recipie_fca5ce_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['campus', 'status'], name='core_paymen_campus__4d6983_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['gateway_order_id'], name='core_paymen_gateway_d6085b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['gateway_payment_id'], name='core_paymen_gateway_e95df5_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsetting',
            index=models.Index(fields=['campus', 'status'], name='core_platfo_campus__d7be7a_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsetting',
            index=models.Index(fields=['key'], name='core_platfo_key_c10b6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platformsetting',
            unique_together={('campus', 'key')},
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['campus', 'year', 'month'], name='core_salary_campus__ac58f4_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['staff_user', 'payment_status'], name='core_salary_staff_u_2fc58a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('campus', 'staff_user', 'month', 'year')},
        ),
    ]
