# Generated by Django 5.2.14 on 2026-06-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ailog_document_messagetemplate_outboundmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank'), ('online', 'Online'), ('upi', 'UPI'), ('net_banking', 'Net banking'), ('wallet', 'Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank'), ('online', 'Online'), ('upi', 'UPI'), ('net_banking', 'Net banking'), ('wallet', 'Wallet')], default='online', max_length=32),
        ),
    ]
