# Generated by Django 5.2.14 on 2026-06-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusmembership',
            name='role',
            field=models.CharField(choices=[('it_admin', 'School Admin'), ('finance_admin', 'Account'), ('teacher', 'Teacher'), ('support', 'Student Portal')], max_length=32),
        ),
    ]
